FROM germaniumhq/ubuntu:16.04
MAINTAINER Bogdan Mustiata <bogdan.mustiata@gmail.com>

RUN apt update -y && \
    apt install -y python2.7 python-pip python-virtualenv && \
    useradd ciplogic -m

USER ciplogic

RUN virtualenv /home/ciplogic/python

